#kubectl label nodes <your-node-name> engineer=vilas
#kubectl get nodes --show-labels

#to remove label 
#kubectl label nodes <your-node-name> engineer-
#We can use the 'nodeSelector' property on the Pod YAML:

apiVersion: v1
kind: Pod
metadata:
  name: cuda-test
spec:
  containers:
    - name: cuda-test
#      image: "k8s.gcr.io/cuda-vector-add:v0.1"
      image: "nginx:latest"
  nodeSelector: # add this
    engineer: vilas # the selection label